services:
  # Web Service - Main Application
  - type: web
    name: neural-network-web
    env: docker
    dockerfilePath: ./neural-network/Dockerfile.web
    dockerContext: ./neural-network
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: DOMAIN
        value: neural-network-chat.onrender.com
      - key: EMAIL
        value: admin@neural-network-chat.onrender.com
      - key: PYTHONUNBUFFERED
        value: 1
      - key: GIN_MODE
        value: release
    healthCheckPath: /api/health
    autoDeploy: true
    
  # Background Worker - Neural Network Processing
  - type: worker
    name: neural-network-worker
    env: docker
    dockerfilePath: ./neural-network/Dockerfile.worker
    dockerContext: ./neural-network
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /app
      - key: REDIS_URL
        fromService:
          type: redis
          name: neural-network-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: neural-network-postgres
          property: connectionString
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: neural-network-postgres
    plan: starter
    region: oregon
    databaseName: neural_db
    user: neural
    ipAllowList: []

  # Redis Cache
  - name: neural-network-redis
    plan: starter
    region: oregon
    ipAllowList: []
